title: Major Training
markdown: kramdown
email: cemrajc+majortraining@gmail.com
baseurl: ""

port: 80

keep_files: [
    '_site/css',
    '_site/js',
    "_site/README.md"
]
exclude: [
    "node_modules/",
    "sass/",
    "js/",
    "CONTRIBUTORS.md",
    "gulpfile.js",
    "package.json",
    "README.md",
    "README(gh-pages).md",
    "*.jignore",
    "*ffs_*"
]