title: Major Training
markdown: kramdown
email: cemrajc+majortraining@gmail.com
baseurl: ""

port: 80

keep_files: [
    '_site/css',
    '_site/js'
]
exclude: [
    "node_modules/",
    "sass/",
    "js/",
    "*.md",
    "*ffs_*"
]